#!/bin/sh

if [ "`whoami`" != "root" ]; then
	echo 'should be root.'
	exit 1
fi

cd /usr/src/linux || exit 1

ts=`date +%s`

if [ ! -f .config ]; then
	echo 'No configuration file. Configuring.'
	make menuconfig
fi

if [ ! -f arch/`uname -m`/boot/bzImage ]; then
	echo 'No kernel found. Compiling.'
	make
fi

echo 'Installing modules'
make modules_install

echo 'Copying new kernel'
cp System.map /boot/System.map.$ts
cp .config /boot/config.$ts
cp arch/`uname -m`/boot/bzImage /boot/vmlinuz.$ts

echo 'Symlink dance'
rm /boot/{vmlinuz,System.map,config}
ln -sv /boot/System.map.$ts /boot/System.map
ln -sv /boot/config.$ts /boot/config
ln -sv /boot/vmlinuz.$ts /boot/vmlinuz
