#!/bin/sh

# --- BEGIN CONFIG

# version to be used (current, 14.1, 13.37, etc.)
version=current
# architecture : 64, arm or nothing (x86)
arch=64
# mirror from which packages should be fetched
mirror=http://slackware.mirrors.ovh.net/ftp.slackware.com/slackware$arch-$version/
# installation directory
root=/mnt/slack64
# packages template
template=templates/base
# timezone
timezone=Europe/Paris
# LANG env variable
lang=en_US.UTF8

# --- END CONFIG

# temporary directory (mktemp -d?)
tmp=/tmp/mkdirinst.$$
# file list (pkgs)
fl=$tmp/FILE_LIST

# some checks
which curl || exit 1
which installpkg || exit 1
mkdir -p $tmp/pkgs/ || exit 1
mkdir -p $root || exit 1
[ -f "$template" ] || exit 1

# Ok, going on

# Download file list
curl $mirror/slackware$arch/FILE_LIST | awk '{ print $NF }' > $fl
# still a few .tgz in this .txz ocean
sed -i '/\.txt$/d; /\.asc/d' $fl

# Download all packages
for p in `cat $template`; do
	(cd $tmp/pkgs; curl -C - -O $mirror/slackware$arch/`grep $p- $fl`)
done

# aaa_base should be first. install other aaa_* while we're here.
installpkg --root $root $tmp/pkg/aaa_*

# Install packages
for p in $tmp/pkgs/*; do
	installpkg --root $root $p
done

# Set timezone
cp /usr/share/zoneinfo/$timezone $root/etc/localtime

# Set LANG
echo "export LANG=$lang" >> $root/etc/profile.d/lang.sh

# Generate /etc/fstab is $root is apparently mounted
grep $root /etc/mtab && \
(
	awk '/'`basename $root`'/ { print $1 "    /    " $3 "    defaults    1  1" }' /etc/mtab  > $tmp/fstab
	grep swap /etc/fstab >> $tmp/fstab
	echo 'devpts    /dev/pts    devpts    gid=5,mode=620    0  0' >> $tmp/fstab
	echo 'proc    /proc    proc    defaults    0  0' >> $tmp/fstab
	echo 'tmpfs    /dev/shm    tmpfs    defaults    0  0' >> $tmp/fstab

	echo '--- BEGIN /etc/fstab'
	cat $tmp/fstab
	echo '--- END /etc/fstab'

	echo 'Ok? ^C to abort, file is ' $tmp/fstab
	read
	# See github.com/heaumer/utils/tree/master/ucol.c
	which ucol &>/dev/null && (ucol -n 5 $tmp/fstab > $root/etc/fstab)
	cp $tmp/fstab $root/etc/
)

rm -rf $tmp
