#!/bin/sh

conf="/etc/mkdirinst.conf"

if [ "$1" != "" ]; then
	conf="$1"
fi

. $conf || exit 1

cat <<EOF
--- BEGIN CONFIG
	version=$version
	arch=$arch
	mirror=$mirror
	root=$root
	template=$template
	timezone=$timezone
	lang=$lang
--- END CONFIG
EOF

echo 'Continue? (^C to abort)'; read

# temporary directory (mktemp -d?)
tmp=/tmp/mkdirinst.$$
# file list (pkgs)
fl=$tmp/FILE_LIST

# some checks
which curl || exit 1
which installpkg || exit 1
mkdir -p $tmp/pkgs/ || exit 1
mkdir -p $root || exit 1
[ -f "$template" ] || exit 1

# Ok, going on

# Download file list
curl $mirror/slackware$arch/FILE_LIST | awk '{ print $NF }' > $fl
# still a few .tgz in this .txz ocean
sed -i '/\.txt$/d; /\.asc/d' $fl

# Download all packages
for p in `cat $template`; do
	(cd $tmp/pkgs; curl -C - -O $mirror/slackware$arch/`grep $p- $fl`)
done

# aaa_base should be first. install other aaa_* while we're here.
installpkg --root $root $tmp/pkg/aaa_*

# Install packages
for p in $tmp/pkgs/*; do
	installpkg --root $root $p
done

# Set timezone
cp /usr/share/zoneinfo/$timezone $root/etc/localtime

# Set LANG
echo "export LANG=$lang" >> $root/etc/profile.d/lang.sh

# Generate /etc/fstab is $root is apparently mounted
grep $root /etc/mtab && \
(
	awk '/'`basename $root`'/ { print $1 "    /    " $3 "    defaults    1  1" }' /etc/mtab  > $tmp/fstab
	grep swap /etc/fstab >> $tmp/fstab
	echo 'devpts    /dev/pts    devpts    gid=5,mode=620    0  0' >> $tmp/fstab
	echo 'proc    /proc    proc    defaults    0  0' >> $tmp/fstab
	echo 'tmpfs    /dev/shm    tmpfs    defaults    0  0' >> $tmp/fstab

	echo '--- BEGIN /etc/fstab'
	cat $tmp/fstab
	echo '--- END /etc/fstab'

	echo 'Ok? ^C to abort, file is ' $tmp/fstab; read
	# See github.com/heaumer/utils/tree/master/ucol.c
	which ucol &>/dev/null && (ucol -n 5 $tmp/fstab > $root/etc/fstab) || \
		cp $tmp/fstab $root/etc/
)

rm -rf $tmp
